[package]
name = "palex"
version = "0.1.0"
authors = ["Ludwig Stecher <ludwig.stecher@gmx.de>"]
edition = "2018"
description = "A fast, small, dependency-free crate for lexing command-line arguments"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
